# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MoCo
version:      0.05
version_from: lib/MoCo.pm
installdirs:  site
requires:
    Cache::Memory:                 
    Class::Trigger:                
    DBD::SQLite:                   
    DBI:                           
    Exporter:                      
    List::MoreUtils:               
    List::Util:                    
    SQL::Abstract:                 

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
